import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import dotenv from 'dotenv';
import { verifyToken, requireAdmin } from './middleware/auth.js';
import adminRoutes from './routes/admin.js';
import authRoutes from './routes/auth.js';
import userRoutes from './routes/user.js';
import chatRoutes from './routes/chat.js';
import checkinRoutes from './routes/checkin.js';
dotenv.config();
const app = express();
const PORT = process.env.PORT || 3001;
app.use(helmet());
app.use(express.json());
app.use(cors({ origin: '*', credentials: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 1000 }));
app.get('/health', (req, res) => res.json({ status: 'ok', time: new Date().toISOString() }));
app.use('/auth', authRoutes);
app.use('/user', userRoutes);
app.use('/admin', verifyToken, requireAdmin, adminRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/check-ins', checkinRoutes);
app.listen(PORT, () => console.log(`🚀 Live on ${PORT}`));
export default app;
